<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwg1q94\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwg1q94/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWwg1q94.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWwg1q94\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWwg1q94\appProdProjectContainer([
    'container.build_hash' => 'Wwg1q94',
    'container.build_id' => 'd8f50fe2',
    'container.build_time' => 1694259374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwg1q94');
